# github actions marketplace
name: Checkout code
on: [push]
jobs:
  build: # these is job name and should be unique
    runs-on: ubuntu-latest # this is oparation system(windows, linux & mac)
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: display the files
        run: ls -la